<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC200" name="Exostar Core Part - Node - 1" tests="2" failures="1" timestamp="22 Feb 2018 10:30:54 GMT" time="45.033" errors="0">
  <testcase name="LoginTest_10023" time="2.476" classname="org.exostar.ts.LoginTC"/>
  <testcase name="LoginTest_10024" time="20.289" classname="org.exostar.ts.LoginTC">
    <failure type="java.lang.AssertionError" message="User not able to enter Password expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User not able to enter Password expected [true] but found [false]
	at org.exostar.ts.LoginTC.LoginTest_10024(LoginTC.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest_10024 -->
</testsuite> <!-- Exostar Core Part - Node - 1 -->
